const app=document.getElementById('app');
const toast=document.getElementById('toast');
const store={get(k,d=null){try{const v=localStorage.getItem(k);return v==null?d:JSON.parse(v)}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
const state={route:location.hash.replace('#/','')||'landing',user:store.get('mjs_user',null),source:localStorage.getItem('mjs_source')||'',processed:localStorage.getItem('mjs_processed')||'',logo:localStorage.getItem('mjs_logo')||'',primary:localStorage.getItem('mjs_primary')||'#081a18',accent:localStorage.getItem('mjs_accent')||'#9dff4b',name:localStorage.getItem('mjs_name')||'YOUR NAME',number:localStorage.getItem('mjs_number')||'10'};
function go(r){location.hash='#/'+r} window.go=go;
window.addEventListener('hashchange',()=>{state.route=location.hash.replace('#/','')||'landing';render()});
function notify(m){toast.textContent=m;toast.classList.add('show');clearTimeout(notify.t);notify.t=setTimeout(()=>toast.classList.remove('show'),2200)}
function hot(cls,route,label=''){return `<button class="hot ${cls}" aria-label="${label||route}" onclick="go('${route}')"></button>`}
function shell(bg,inner=''){return `<div class="stage"><div class="mockup ${bg}">${inner}</div></div>`}
function landing(){return shell('home-bg',`${hot('home-sign','login','Sign in')}${hot('home-get','login','Get started')}${hot('home-start','login','Start designing')}${hot('home-card1','vector','Image to vector')}${hot('home-card2','customize','Customize')}${hot('home-card3','preview','Preview')}${hot('home-card4','projects','Downloads')}`)}
function login(){return shell('login-bg',`<button class="login-back" onclick="go('landing')">Back</button><form class="login-form" onsubmit="return doLogin(event)"><input id="email" autocomplete="username" placeholder="Email or Username" required><input id="password" autocomplete="current-password" type="password" placeholder="Password" required><button class="login-submit">Login →</button><div class="login-alt">OR</div><button class="guest-btn" type="button" onclick="guestLogin()">◯ &nbsp; Continue as Guest</button></form><button class="login-create" onclick="createLocalAccount()">Create Account</button>`)}
window.doLogin=async e=>{e.preventDefault();const email=document.getElementById('email').value.trim(),password=document.getElementById('password').value;let user={name:email.includes('@')?email.split('@')[0]:email,email,role:'Designer',plan:'Pro Plan'};try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password})});if(r.ok){const d=await r.json();user=d.user||user;if(d.token)localStorage.setItem('mjs_token',d.token)}}catch{}state.user=user;store.set('mjs_user',user);notify('Welcome back');go('dashboard');return false};
window.guestLogin=()=>{state.user={name:'Guest Designer',role:'Designer',plan:'Guest'};store.set('mjs_user',state.user);go('dashboard')};
window.createLocalAccount=()=>{const name=prompt('Your name','Designer');if(!name)return;state.user={name,role:'Designer',plan:'Free'};store.set('mjs_user',state.user);notify('Account created locally');go('dashboard')};
function topHot(){return `${hot('top-home','dashboard','Home')}${hot('top-design','customize','Design')}${hot('top-prod','production','Production')}${hot('top-projects','projects','My Projects')}${hot('top-templates','templates','Templates')}${hot('top-menu','menu','Menu')}`}
function dashboard(){if(!state.user)return login();return shell('dash-bg',`${topHot()}${hot('dash-vector','vector','Image to vector')}${hot('dash-file','fileconvert','File convert')}${hot('dash-bulk','bulk','Bulk production')}${hot('dash-recent','projects','Recent designs')}`)}
function menu(){if(!state.user)return login();return shell('menu-bg',`${hot('menu-close','dashboard','Close')}${hot('menu-dashboard','dashboard','Dashboard')}${hot('menu-vector','vector','Image to vector')}${hot('menu-custom','customize','Customize design')}${hot('menu-preview','preview','Preview studio')}${hot('menu-templates','templates','Templates')}${hot('menu-file','fileconvert','File convert')}${hot('menu-bulk','bulk','Bulk production')}`)}
function fileToDataURL(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
async function cleanImage(data){return new Promise(resolve=>{const img=new Image();img.onload=()=>{const max=900,sc=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*sc));c.height=Math.max(1,Math.round(img.height*sc));const x=c.getContext('2d');x.drawImage(img,0,0,c.width,c.height);const id=x.getImageData(0,0,c.width,c.height),p=id.data;const corners=[[0,0],[c.width-1,0],[0,c.height-1],[c.width-1,c.height-1]].map(([cx,cy])=>{const i=(cy*c.width+cx)*4;return[p[i],p[i+1],p[i+2]]});const bg=corners.reduce((a,b)=>a.map((v,i)=>v+b[i]),[0,0,0]).map(v=>v/4);for(let i=0;i<p.length;i+=4){const d=Math.hypot(p[i]-bg[0],p[i+1]-bg[1],p[i+2]-bg[2]);if(d<52)p[i+3]=0;else{p[i]=Math.round(p[i]/24)*24;p[i+1]=Math.round(p[i+1]/24)*24;p[i+2]=Math.round(p[i+2]/24)*24}}x.putImageData(id,0,0);resolve(c.toDataURL('image/png'))};img.src=data})}
window.handleVectorUpload=async e=>{const f=e.target.files?.[0];if(!f)return;state.source=await fileToDataURL(f);localStorage.setItem('mjs_source',state.source);notify('AI cleanup running…');state.processed=await cleanImage(state.source);localStorage.setItem('mjs_processed',state.processed);render();notify('Background cleanup complete')};
window.useVectorAsLogo=()=>{if(!state.processed)return notify('Upload an image first');state.logo=state.processed;localStorage.setItem('mjs_logo',state.logo);notify('Artwork added to Design Studio');go('customize')};
function downloadBlob(name,blob){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
window.downloadVector=()=>{if(!state.processed)return notify('Upload an image first');const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="1200" viewBox="0 0 1200 1200"><image href="${state.processed}" width="1200" height="1200" preserveAspectRatio="xMidYMid meet"/></svg>`;downloadBlob('my-jersey-vector.svg',new Blob([svg],{type:'image/svg+xml'}));notify('SVG exported')};
function vector(){if(!state.user)return login();return shell('vector-bg',`${topHot()}<label class="hot vector-upload" aria-label="Upload image"><input type="file" accept="image/*,.svg,.pdf" onchange="handleVectorUpload(event)"></label>${state.source?`<img class="vector-preview-img vector-original" src="${state.source}">`:''}${state.processed?`<img class="vector-preview-img vector-clean" src="${state.processed}"><div class="vector-status"><b>AI cleanup complete</b>✓ Background removed<br>✓ Color cleanup<br>✓ Transparent output</div>`:''}<button class="hot vector-use" onclick="useVectorAsLogo()" aria-label="Use in design"></button><button class="hot vector-download" onclick="downloadVector()" aria-label="Download files"></button>`)}
function forge(){if(!state.user)return login();return shell('forge-bg',`${topHot()}<label class="hot" style="left:3%;top:51%;width:17%;height:6%"><input style="position:absolute;inset:0;opacity:0" type="file" accept="image/*" onchange="handleVectorUpload(event)"></label><button class="hot" style="left:83%;top:77%;width:15%;height:6%" onclick="downloadVector()"></button>`)}
function jerseySVG(front=true){const logo=state.logo?`<image href="${state.logo}" x="118" y="90" width="84" height="82" preserveAspectRatio="xMidYMid meet"/>`:`<path d="M125 106l35-20 35 20-8 45-27 16-27-16z" fill="${state.accent}"/><text x="160" y="135" text-anchor="middle" font-size="25" font-weight="900" fill="#07140f">MJ</text>`;return `<svg class="jersey" viewBox="0 0 320 380" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${state.primary}"/><stop offset="1" stop-color="#020808"/></linearGradient></defs><path d="M82 70l40-32q38-14 76 0l40 32 62 28-28 62-38-18-6 206H92l-6-206-38 18-28-62z" fill="url(#g)" stroke="${state.accent}" stroke-width="4"/><path d="M122 38q38 48 76 0l-15-11q-23 28-46 0z" fill="#020808" stroke="${state.accent}" stroke-width="4"/><path d="M79 72l42 25-18 31-42-23zm162 0l-42 25 18 31 42-23z" fill="${state.accent}" opacity=".9"/><path d="M102 135l35-40 18 248h-34zm116 0l-35-40-18 248h34z" fill="${state.accent}" opacity=".18"/>${front?`${logo}<text x="160" y="220" text-anchor="middle" fill="#fff" font-weight="900" font-size="25">TIGERS</text><text x="160" y="292" text-anchor="middle" fill="${state.accent}" stroke="#fff" stroke-width="2" font-weight="900" font-size="86">${escapeHtml(state.number)}</text>`:`<text x="160" y="140" text-anchor="middle" fill="#fff" font-weight="800" font-size="24">${escapeHtml(state.name)}</text><text x="160" y="260" text-anchor="middle" fill="none" stroke="#fff" stroke-width="4" font-weight="900" font-size="110">${escapeHtml(state.number)}</text>`}</svg>`}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function customize(){if(!state.user)return login();return shell('custom-bg',`${topHot()}<div class="custom-front">${jerseySVG(true)}</div><div class="custom-back">${jerseySVG(false)}</div><div class="custom-panel"><input class="control color-primary" type="color" value="${state.primary}" onchange="setPrimary(this.value)"><input class="control color-accent" type="color" value="${state.accent}" onchange="setAccent(this.value)"><input class="control logo-file" type="file" accept="image/*" onchange="setLogo(event)"><input class="control name-input" value="${escapeHtml(state.name)}" placeholder="Player name" oninput="setName(this.value)"><input class="control num-input" value="${escapeHtml(state.number)}" placeholder="10" oninput="setNumber(this.value)"><button class="control save-design" onclick="saveDesign()">Save Design</button><button class="control continue-btn" onclick="go('preview')">Continue to Download →</button></div><div class="ai-box"><input id="aiPrompt" placeholder="Describe your design change…"><button onclick="runAICommand()">➜</button></div>`)}
window.setPrimary=v=>{state.primary=v;localStorage.setItem('mjs_primary',v);render()};window.setAccent=v=>{state.accent=v;localStorage.setItem('mjs_accent',v);render()};window.setName=v=>{state.name=v;localStorage.setItem('mjs_name',v);document.querySelector('.custom-back')&&(document.querySelector('.custom-back').innerHTML=jerseySVG(false))};window.setNumber=v=>{state.number=v;localStorage.setItem('mjs_number',v);document.querySelector('.custom-front')&&(document.querySelector('.custom-front').innerHTML=jerseySVG(true));document.querySelector('.custom-back')&&(document.querySelector('.custom-back').innerHTML=jerseySVG(false))};
window.setLogo=async e=>{const f=e.target.files?.[0];if(!f)return;state.logo=await fileToDataURL(f);localStorage.setItem('mjs_logo',state.logo);render()};
window.saveDesign=()=>{const list=store.get('mjs_projects',[]);list.unshift({id:Date.now(),name:state.name,number:state.number,primary:state.primary,accent:state.accent,logo:state.logo,created:new Date().toISOString()});store.set('mjs_projects',list.slice(0,30));notify('Design saved')};
window.runAICommand=async()=>{const q=document.getElementById('aiPrompt')?.value.trim();if(!q)return;const l=q.toLowerCase();if(l.includes('green'))setAccent('#9dff4b');if(l.includes('blue'))setAccent('#2e7cff');if(l.includes('red'))setAccent('#ff4040');if(l.match(/number\s*\d+/)){const n=l.match(/number\s*(\d+)/)[1];state.number=n;localStorage.setItem('mjs_number',n)}try{const r=await fetch('/api/ai',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({prompt:q})});if(r.ok)notify('AI command applied')}catch{notify('Command applied locally')}render()};
function preview(){if(!state.user)return login();return simple('Preview Studio','Inspect your front and back design before production.',`<div class="grid-cards"><div class="card">${jerseySVG(true)}<button onclick="downloadCurrentSVG(true)">Download Front SVG</button></div><div class="card">${jerseySVG(false)}<button onclick="downloadCurrentSVG(false)">Download Back SVG</button></div><div class="card"><h2>Production Ready</h2><p>Transparent master artwork, front/back SVG and print-ready package.</p><button onclick="downloadPackage()">Download ZIP Package</button></div></div>`)}
window.downloadCurrentSVG=front=>downloadBlob(`jersey-${front?'front':'back'}.svg`,new Blob([jerseySVG(front).replace('class="jersey"','')],{type:'image/svg+xml'}));
function crc32(bytes){let c=-1;for(const b of bytes){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xEDB88320:0)}return(c^-1)>>>0}function u16(n){return new Uint8Array([n&255,n>>8&255])}function u32(n){return new Uint8Array([n&255,n>>8&255,n>>16&255,n>>24&255])}function join(a){let n=a.reduce((x,y)=>x+y.length,0),o=new Uint8Array(n),p=0;for(const x of a){o.set(x,p);p+=x.length}return o}function zip(files){const enc=new TextEncoder(),local=[],central=[];let off=0;for(const f of files){const name=enc.encode(f.name),data=enc.encode(f.data),crc=crc32(data),lh=join([u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),name,data]);local.push(lh);central.push(join([u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(off),name]));off+=lh.length}const l=join(local),c=join(central),end=join([u32(0x06054b50),u16(0),u16(0),u16(files.length),u16(files.length),u32(c.length),u32(l.length),u16(0)]);return new Blob([l,c,end],{type:'application/zip'})}
window.downloadPackage=()=>downloadBlob('my-jersey-production-package.zip',zip([{name:'front.svg',data:jerseySVG(true).replace('class="jersey"','')},{name:'back.svg',data:jerseySVG(false).replace('class="jersey"','')},{name:'production.txt',data:`Name: ${state.name}\nNumber: ${state.number}\nPrimary: ${state.primary}\nAccent: ${state.accent}`}]))
function projects(){if(!state.user)return login();const items=store.get('mjs_projects',[]);return simple('Recent Designs','Saved jersey projects and production drafts.',items.length?`<div class="grid-cards">${items.map(p=>`<div class="card"><h2>${escapeHtml(p.name)} #${escapeHtml(p.number)}</h2><p>${new Date(p.created).toLocaleString()}</p><button onclick="loadProject(${p.id})">Open Design</button></div>`).join('')}</div>`:`<div class="card"><h2>No saved designs yet</h2><p>Create a design and press Save Design.</p><button onclick="go('customize')">Create Design</button></div>`)}
window.loadProject=id=>{const p=store.get('mjs_projects',[]).find(x=>x.id===id);if(!p)return;Object.assign(state,{name:p.name,number:p.number,primary:p.primary,accent:p.accent,logo:p.logo});['name','number','primary','accent','logo'].forEach(k=>localStorage.setItem('mjs_'+k,state[k]||''));go('customize')};
function simple(title,desc,content){return `<div class="simple-page"><header class="simple-top"><div class="brand-text">My Jersey <span>Studio</span></div><nav><a href="#/dashboard">Home</a><a href="#/vector">Image To Vector</a><a href="#/customize">Customize</a><a href="#/projects">My Projects</a></nav><button style="margin-left:auto" class="floating-back" onclick="go('menu')">☰ Menu</button></header><main class="simple-content"><h1>${title.replace(/(\w+)$/,'<span>$1</span>')}</h1><p>${desc}</p>${content}</main></div>`}
function templates(){return simple('Jersey Templates','Starter looks based on your supplied studio direction.',`<div class="grid-cards"><div class="card"><h2>Neon Tiger</h2><p>Black + neon green, aggressive esports style.</p><button onclick="applyPreset('#071411','#9dff4b')">Use Template</button></div><div class="card"><h2>Blue Lightning</h2><p>Deep navy with electric blue accent.</p><button onclick="applyPreset('#071225','#2e7cff')">Use Template</button></div><div class="card"><h2>Red Fury</h2><p>Black/red production-ready jersey style.</p><button onclick="applyPreset('#180707','#ff4141')">Use Template</button></div></div>`)}
window.applyPreset=(a,b)=>{state.primary=a;state.accent=b;localStorage.setItem('mjs_primary',a);localStorage.setItem('mjs_accent',b);go('customize')};
function fileconvert(){return simple('File Convert','Convert and package design files for the production workflow.',`<div class="card"><h2>Image / Vector Converter</h2><p>Use Image To Vector for AI cleanup and SVG export. PNG/JPG files can also be added to the production package.</p><button onclick="go('vector')">Open Image To Vector</button></div>`)}
function bulk(){return simple('Bulk Production','Personalize many jersey names and numbers from a roster.',`<div class="card"><h2>CSV Roster</h2><p>CSV format: name,number,size,qty,team</p><input id="csv" type="file" accept=".csv,text/csv"><button onclick="parseCSV()">Load Roster</button><pre id="csvout"></pre></div>`)}
window.parseCSV=()=>{const f=document.getElementById('csv').files?.[0];if(!f)return notify('Choose a CSV file');const r=new FileReader();r.onload=()=>{const rows=String(r.result).trim().split(/\r?\n/).slice(1).map(x=>x.split(','));store.set('mjs_bulk',rows);document.getElementById('csvout').textContent=`${rows.length} players loaded`;notify('Roster loaded')};r.readAsText(f)};
function production(){return simple('Production Center','Validate the current jersey before final export.',`<div class="grid-cards"><div class="card"><h2>Current Master</h2><p>${escapeHtml(state.name)} #${escapeHtml(state.number)}</p><p>Primary ${state.primary}<br>Accent ${state.accent}</p></div><div class="card"><h2>Validation</h2><p>✓ Front generated<br>✓ Back generated<br>✓ SVG export enabled<br>✓ Factory ZIP enabled</p></div><div class="card"><h2>Export</h2><button onclick="downloadPackage()">Download Factory ZIP</button></div></div>`)}
function arch(){return `<div class="stage"><div class="mockup arch arch-bg"></div></div>`}
function render(){const routes={landing,login,dashboard,menu,vector,forge,customize,preview,projects,templates,fileconvert,bulk,production,architecture:arch};app.innerHTML=(routes[state.route]||landing)()}
render();
